# Generated by Django 6.0.3 on 2026-03-12 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.URLField(default='https://i.pinimg.com/736x/76/f3/f3/76f3f3007969fd3b6db21c744e1ef289.jpg')),
                ('Full_Name', models.CharField(default='Max Joel')),
                ('Website_or_Portfolio', models.URLField()),
                ('Location', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=20)),
                ('Company_Name', models.CharField(blank=True, max_length=255)),
                ('Position', models.CharField(max_length=100)),
                ('Industry', models.CharField(max_length=100)),
                ('ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Seeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.URLField(default='https://i.pinimg.com/736x/76/f3/f3/76f3f3007969fd3b6db21c744e1ef289.jpg')),
                ('Full_Name', models.CharField(default='Max Joel')),
                ('Website_or_Portfolio', models.URLField()),
                ('Location', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=20)),
                ('Resume', models.URLField(blank=True)),
                ('Skills', models.CharField(max_length=255)),
                ('Experience', models.TextField()),
                ('Education', models.TextField()),
                ('ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
