# Generated by Django 6.0.3 on 2026-03-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('REACT_NATIVE', 'React Native'), ('FLUTTER', 'Flutter'), ('DJANGO', 'Django'), ('NODE_JS', 'Node.js'), ('HTML_CSS', 'HTML/CSS'), ('JAVASCRIPT', 'JavaScript'), ('TYPESCRIPT', 'TypeScript'), ('PYTHON', 'Python'), ('JAVA', 'Java'), ('C_PLUS_PLUS', 'C++'), ('UI_UX', 'UI/UX Design'), ('FIGMA', 'Figma'), ('ADOBE_PHOTOSHOP', 'Adobe Photoshop'), ('ADOBE_ILLUSTRATOR', 'Adobe Illustrator'), ('GRAPHIC_DESIGN', 'Graphic Design'), ('DATA_ANALYSIS', 'Data Analysis'), ('MACHINE_LEARNING', 'Machine Learning'), ('AI', 'Artificial Intelligence'), ('DEEP_LEARNING', 'Deep Learning'), ('CONTENT_WRITING', 'Content Writing'), ('SEO', 'SEO'), ('DIGITAL_MARKETING', 'Digital Marketing'), ('VIDEO_EDITING', 'Video Editing'), ('CYBER_SECURITY', 'Cyber Security')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('MOBILE_APP', 'Mobile App Development'), ('WEB_DEV', 'Web Development'), ('UI_UX', 'UI/UX Design'), ('GRAPHIC_DESIGN', 'Graphic Design'), ('DATA_SCIENCE', 'Data Science & AI'), ('DEVOPS', 'DevOps & Cloud'), ('GAME_DEV', 'Game Development'), ('CONTENT_WRITING', 'Content Writing'), ('DIGITAL_MARKETING', 'Digital Marketing'), ('VIDEO_EDITING', 'Video Editing'), ('CYBER_SECURITY', 'Cyber Security'), ('BLOCKCHAIN', 'Blockchain Development'), ('E_COMMERCE', 'E-commerce Development'), ('QA_TESTING', 'QA & Testing'), ('OTHER', 'Other')], max_length=50)),
                ('price', models.PositiveIntegerField(default=30)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('INR', 'Indian Rupee (₹)'), ('NPR', 'Nepalese Rupee (Rs)'), ('AUD', 'Australian Dollar (A$)'), ('CAD', 'Canadian Dollar (C$)'), ('JPY', 'Japanese Yen (¥)'), ('CNY', 'Chinese Yuan (¥)')], max_length=5)),
                ('duration_days', models.PositiveIntegerField()),
                ('is_remote', models.BooleanField(default=False)),
                ('experience_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('PROFESSIONAL', 'Professional')], max_length=20)),
                ('proposals_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('skills_required', models.ManyToManyField(blank=True, to='jobs.skill')),
            ],
        ),
    ]
